### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by raphaelsoul** [Metnew/webpack-pkg-plugin#3]
got warning when compiling my bundled app which claims like following
```
(node:58199) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

versions are here. Any idea to handle this?
```
├── pkg@4.3.1
├── webpack@4.4.1
├── webpack-cli@2.0.13
├── webpack-merge@4.1.2
├── webpack-node-externals@1.7.2
└── webpack-pkg-plugin@1.0.3
```

**Comment by Metnew** [comment]
Hi @raphaelsoul, that's because this plugin supports only Webpack v3. 
I'm currently not so interested in supporting Webpack v4 due to low community (and my own) interest. 
But I can review/merge PRs bringing this feature.

**Comment by Metnew** [comment]
@BryanSummers14 added a support for Webpack v4! 🎉
